### ISSUE TITLE
Are settings saved even when ditherig is not running?

### ISSUE THREAD

**Issue by githubbapoopa** [skawamoto0/ditherig#1]
Hi there.
Great tool.
Are the settings saved even when ditherig is not running or must it be running all the time?
How does it work exactly?

**Comment by skawamoto0** [comment]
Hello,
If you quit the app, the dithering settings will be saved until the device status is not changed, for example opening or closing the lid of the notebook, connecting or disconnecting external displays, or suspending or resuming the system.
I recommend you to keep running the app, and it tries to keep the settings automatically.
