### ISSUE TITLE
Settings not restored after display off timeout

### ISSUE THREAD

**Issue by Tonux599** [skawamoto0/ditherig#2]
Hey there,

This application works perfectly when resuming my system from power off or suspend, as well as opening the laptop lid.

However, I have my display set to power off after a period of time, when waking the display (via mouse/keyboard input) the dithering settings are not restored. This can also be reproduce by locking Windows, which then turns off the screen after a short period and waking the screen.

Let me know if you have any suggestions.

Thanks!

**Comment by skawamoto0** [comment]
Hello, please try Ver 2.2.
