### ISSUE TITLE
Raptor Lake works?

### ISSUE THREAD

**Issue by LoHamer** [skawamoto0/ditherig#7]
Doesn't seem to be working with Intel UHD 770. Using an i9-13900K.

**Comment by skawamoto0** [comment]
Hello, it cannot detect the graphics of Intel 13th gen CPUs automatically because I have not confirmed that it can work with them, but it may work if you identify it manually.

**Comment by skawamoto0** [comment]
Now, Ver 2.1 supports some of them and Ver 2.2 does the all (I assume that Intel will not launch any new models of the 13th gen).

**Comment by LoHamer** [comment]
Just a quick note to express my sincere gratitude for the update. Your kindness in also updating this thread and letting me know means a lot. Your commitment to helping others is truly admirable.
